"""Build js/words.js from data/csw12.txt.

data/csw12.txt is Collins Scrabble Words 2012 (CSW12), words of 3+ letters,
one lowercase word per line. CSW12 reproduces the "possible words" counts
seen in GamePigeon Anagrams exactly (RDIEPT -> 61, ICIEMLA -> 69), where
other editions (CSW07/SOWPODS, CSW15, CSW19, CSW21, TWL/NWL, ENABLE) don't.

The word list is (C) HarperCollins. Keep it in private repositories only.

Source: https://github.com/scrabblewords/scrabblewords (words/British/CSW12.txt)
Regenerate data/csw12.txt from that file with:
    python3 tools/build_words.py --from-raw path/to/CSW12.txt

Usage:  python3 tools/build_words.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "csw12.txt"


def from_raw(raw_path):
    # Raw file: "WORD definition..." per line, plus '#' comment lines.
    words = set()
    for line in Path(raw_path).read_text(encoding="utf-8", errors="ignore").splitlines():
        tok = line.split()
        if tok and re.fullmatch(r"[A-Za-z]+", tok[0]) and len(tok[0]) >= 3:
            words.add(tok[0].lower())
    DATA.write_text("\n".join(sorted(words)) + "\n")
    print(f"wrote {DATA.relative_to(ROOT)}: {len(words)} words")


def main():
    if len(sys.argv) == 3 and sys.argv[1] == "--from-raw":
        from_raw(sys.argv[2])
    words = sorted(set(DATA.read_text().split()))
    assert all(w.isascii() and w.isalpha() and w.islower() and len(w) >= 3 for w in words)

    out = ROOT / "js" / "words.js"
    out.write_text(
        "// Generated by tools/build_words.py - do not edit by hand.\n"
        "// Collins Scrabble Words 2012 (CSW12), words of 3+ letters.\n"
        "// Word list (C) HarperCollins.\n"
        f"// {len(words)} words.\n"
        'var GP_WORDS = "' + " ".join(words) + '";\n'
        "if (typeof module === 'object' && module.exports) module.exports = GP_WORDS;\n"
    )
    print(f"wrote {out.relative_to(ROOT)}: {len(words)} words")


if __name__ == "__main__":
    main()
