"""Build js/words.js from the word lists in data/.

Sources (both from https://github.com/k-gerner/Game-Pigeon-Solvers):
  data/letters7.txt   anagrams/letters7.txt  - 3-7 letter words (Anagrams)
  data/letters10.txt  wordhunt/letters10.txt - 3-10 letter words (Word Hunt)

letters10 is a superset of letters7 that agrees with it exactly for words of
7 letters or fewer, so words.js only needs to embed letters10. The app filters
it to <= 7 letters for Anagrams. This script checks that assumption.

Usage:  python3 tools/build_words.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(name):
    words = (ROOT / "data" / name).read_text().split()
    assert all(w.isascii() and w.isalpha() and w.islower() for w in words), name
    return words


def main():
    l7 = set(load("letters7.txt"))
    l10 = sorted(set(load("letters10.txt")))
    assert l7 == {w for w in l10 if len(w) <= 7}, "letters7 != letters10 (<=7)"
    assert min(map(len, l10)) >= 3

    out = ROOT / "js" / "words.js"
    out.write_text(
        "// Generated by tools/build_words.py - do not edit by hand.\n"
        "// Source: k-gerner/Game-Pigeon-Solvers wordhunt/letters10.txt\n"
        "// (identical to anagrams/letters7.txt for words of <= 7 letters).\n"
        f"// {len(l10)} words.\n"
        'var GP_WORDS = "' + " ".join(l10) + '";\n'
        "if (typeof module === 'object' && module.exports) module.exports = GP_WORDS;\n"
    )
    print(f"wrote {out.relative_to(ROOT)}: {len(l10)} words ({len(l7)} for Anagrams)")


if __name__ == "__main__":
    main()
